[package]
name = "nyvrax-reporters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

description = "Output reporters for Nyvrax"

[dependencies]
nyvrax-core.workspace = true
serde_json.workspace = true
thiserror.workspace = true